### ISSUE TITLE
Add query library for run time features

### ISSUE THREAD

**Issue by patricksimpson** [sparkbox/featurama#11]
I'd like to add a query library to enable runtime flags based on a query parameter.

**Comment by bryanbraun** [comment]
You don't need to add a query library to featurama to do this. You can use whatever query library you already use in your client side JS. For example:

To enable a "redesign" feature with: `https://example.com?redesign=true`

```js
module.exports = {
  featureName: 'redesign',
  jsFiles: [],
  buildTimeEnabled: true,
  runTimeEnabled: function() {
    return !!query.get('redesign');
  }
};
```
